spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercado?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: rodrigo321
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8081